export const ERROR_CODE = {
    // AUTH
    AUTH_INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    AUTH_UNAUTHORIZED: 'UNAUTHORIZED',
    AUTH_REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
    AUTH_REFRESH_TOKEN_REVOKED: 'REFRESH_TOKEN_REVOKED',
    AUTH_USER_NOT_FOUND: 'INVALID_USER',
  
    // USER
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  
    // PROVIDER
    PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
    PROVIDER_INACTIVE: 'PROVIDER_INACTIVE',
  
    // CHANNEL
    CHANNEL_NOT_FOUND: 'CHANNEL_NOT_FOUND',
    CHANNEL_INACTIVE: 'CHANNEL_INACTIVE',
  
    // PAYMENT
    PAYMENT_CREATE_FAILED: 'PAYMENT_CREATE_FAILED',
    PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  
    // TRANSACTION
    TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  
    // WEBHOOK
    WEBHOOK_INVALID_SIGNATURE: 'WEBHOOK_INVALID_SIGNATURE',
  
    // RATE LIMIT
    TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',

    // INTERNAL
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const; 